#!/bin/bash

LOGDIR=/var/log/lagom

mkdir -p $LOGDIR

docker run -d                    \
        --restart unless-stopped \
        --name=lagom             \
        -v $LOGDIR:$LOGDIR       \
        -p 443:8443              \
        jfacorro/lagom:latest
