#!/bin/bash

LOGDIR=/var/log/lagom

mkdir -p $LOGDIR

docker run -d                    \
        --restart unless-stopped \
        --name=lagom             \
        -v $LOGDIR:$LOGDIR       \
        -p 8080:8080             \
        jfacorro/lagom:latest
